### ISSUE TITLE
TeamCity Windows Tray Notifier

### ISSUE THREAD

**Issue by kkirpichnikov** [JetBrains/teamcity-azure-active-directory#30]
TeamCity Enterprise 2017.1.2 (build 46812)
Trying to login through Tray Notifier with Azure Active Directory
Sometimes it works some times it doesn't. 
After three attempts the tray notifier window disappears. 
After 6 - 10 attempts I am getting this message and when I close the message it works. If I close the tray and open it again, it doesn't work again.
![2017-08-02 10_25_33-login to teamcity](https://user-images.githubusercontent.com/13055750/28878752-337942a6-776e-11e7-9272-1ea638156c24.png)
![2017-08-02 10_25_07-login to teamcity](https://user-images.githubusercontent.com/13055750/28878913-aebf8844-776e-11e7-8e72-78e0d8dc23f5.png)

OS Name	Microsoft Windows 10 Enterprise
Version	10.0.15063 Build 15063

**Comment by kkirpichnikov** [comment]
Some logs from teamcity-server.log
 INFO - s.buildServer.AUTH.SessionUser - Successful login for user 'User.Name@company_name.com' (User Name) {id=56} with auth module "HTTP-AAD" for session 
from client 11.11.111.11:52 751, no associated user

After third attempt
 ERROR -   jetbrains.buildServer.SERVER - Error javax.servlet.jsp.JspException: java.lang.IllegalStateException: getAttribute: Session already invalidated while processing request: GE
T '/win32/login.html', from client 11.11.111.11:62356, no associated user
javax.servlet.jsp.JspException: java.lang.IllegalStateException: getAttribute: Session already invalidated
        at org.apache.jsp.plugins.WindowsTray.login_jsp$Helper.invoke(login_jsp.java:567)
        at org.apache.jsp.tag.web.externalPage_tag.doTag(externalPage_tag.java:208)
        at org.apache.jsp.plugins.WindowsTray.login_jsp._jspx_meth_bs_005fexternalPage_005f0(login_jsp.java:208)
        at org.apache.jsp.plugins.WindowsTray.login_jsp._jspService(login_jsp.java:145)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
        at jetbrains.spring.web.TeamCityJSPServletImpl.access$001(TeamCityJSPServletImpl.java:15)
        at jetbrains.spring.web.TeamCityJSPServletImpl$2.apply(TeamCityJSPServletImpl.java:2)
        at jetbrains.buildServer.util.Util.doUnderContextClassLoader(Util.java:78)
        at jetbrains.spring.web.TeamCityJSPServletImpl.service(TeamCityJSPServletImpl.java:19)

**Comment by dtretyakov** [comment]
Duplicates #11
